version: '3.9'

services:
  pg_eshop:
    image: postgres:17.0
    environment:
      POSTGRES_DB: "eshop"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
      #- ./init-scripts:/docker-entrypoint-initdb.d
      
volumes:
  pgdata: